Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# calculate difference between measured and reference values
index_list = numpy.arange(76,121)
ref_DRO = r1_ref[index_list]
r1_MJT_DRO = r1_MJT[index_list]
r1_Mcgill_DRO = r1_Mcgill[index_list]
r1_ST_DRO = r1_ST[index_list]
r1_OG_DRO = r1_OG[index_list]

diff_MJT = r1_MJT_DRO - ref_DRO
diff_Mcgill = r1_Mcgill_DRO - ref_DRO
diff_ST = r1_ST_DRO - ref_DRO
diff_OG = r1_OG_DRO - ref_DRO

pyplot.figure(1)
pyplot.plot(ref_DRO, diff_MJT, "ob", label=label_MJT)
pyplot.plot(ref_DRO, diff_Mcgill,"or",label=label_Mcgill)
pyplot.plot(ref_DRO, diff_ST,"og",label=label_ST)
pyplot.plot(ref_DRO, diff_OG,"om",label=label_OG)
pyplot.title('Differences for DRO data')
pyplot.xlabel('$r1_{ref}$ ($s^{-1}$)', fontsize=14)
pyplot.ylabel('$\Delta r1$ ($s^{-1}$)', fontsize=14)
pyplot.legend()
pyplot.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_get_list_axis[0;34m(self, key, axis)[0m
[1;32m   1481[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1482[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mobj[0m[0;34m.[0m[0m_take_with_is_copy[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1483[0m         [0;32mexcept[0m [0mIndexError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/series.py[0m in [0;36m_take_with_is_copy[0;34m(self, indices, axis)[0m
[1;32m    922[0m         """
[0;32m--> 923[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mtake[0m[0;34m([0m[0mindices[0m[0;34m=[0m[0mindices[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    924[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/series.py[0m in [0;36mtake[0;34m(self, indices, axis, is_copy, **kwargs)[0m
[1;32m    907[0m         [0mindices[0m [0;34m=[0m [0mensure_platform_int[0m[0;34m([0m[0mindices[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 908[0;31m         [0mnew_index[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mindex[0m[0;34m.[0m[0mtake[0m[0;34m([0m[0mindices[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    909[0m         [0mnew_values[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_values[0m[0;34m.[0m[0mtake[0m[0;34m([0m[0mindices[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mtake[0;34m(self, indices, axis, allow_fill, fill_value, **kwargs)[0m
[1;32m   1112[0m         [0;32mif[0m [0misinstance[0m[0;34m([0m[0mvalues[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mndarray[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1113[0;31m             taken = algos.take(
[0m[1;32m   1114[0m                 [0mvalues[0m[0;34m,[0m [0mindices[0m[0;34m,[0m [0mallow_fill[0m[0;34m=[0m[0mallow_fill[0m[0;34m,[0m [0mfill_value[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0m_na_value[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/algorithms.py[0m in [0;36mtake[0;34m(arr, indices, axis, allow_fill, fill_value)[0m
[1;32m   1440[0m         [0;31m# NumPy style[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1441[0;31m         [0mresult[0m [0;34m=[0m [0marr[0m[0;34m.[0m[0mtake[0m[0;34m([0m[0mindices[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1442[0m     [0;32mreturn[0m [0mresult[0m[0;34m[0m[0;34m[0m[0m

[0;31mIndexError[0m: cannot do a non-empty take from an empty axes.

The above exception was the direct cause of the following exception:

[0;31mIndexError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_1962/536595609.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0mr1_Mcgill_DRO[0m [0;34m=[0m [0mr1_Mcgill[0m[0;34m[[0m[0mindex_list[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0mr1_ST_DRO[0m [0;34m=[0m [0mr1_ST[0m[0;34m[[0m[0mindex_list[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m [0mr1_OG_DRO[0m [0;34m=[0m [0mr1_OG[0m[0;34m[[0m[0mindex_list[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0mdiff_MJT[0m [0;34m=[0m [0mr1_MJT_DRO[0m [0;34m-[0m [0mref_DRO[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/series.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    983[0m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_values[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    984[0m [0;34m[0m[0m
[0;32m--> 985[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_with[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    986[0m [0;34m[0m[0m
[1;32m    987[0m     [0;32mdef[0m [0m_get_with[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/series.py[0m in [0;36m_get_with[0;34m(self, key)[0m
[1;32m   1020[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0mkey[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m   1021[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1022[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0miloc[0m[0;34m[[0m[0mkey[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1023[0m [0;34m[0m[0m
[1;32m   1024[0m         [0;31m# handle the dup indexing case GH#4246[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    965[0m [0;34m[0m[0m
[1;32m    966[0m             [0mmaybe_callable[0m [0;34m=[0m [0mcom[0m[0;34m.[0m[0mapply_if_callable[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mobj[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 967[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_axis[0m[0;34m([0m[0mmaybe_callable[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    968[0m [0;34m[0m[0m
[1;32m    969[0m     [0;32mdef[0m [0m_is_scalar_access[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m:[0m [0mtuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1509[0m         [0;31m# a list of integers[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1510[0m         [0;32melif[0m [0mis_list_like_indexer[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1511[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_list_axis[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1512[0m [0;34m[0m[0m
[1;32m   1513[0m         [0;31m# a single integer[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_get_list_axis[0;34m(self, key, axis)[0m
[1;32m   1483[0m         [0;32mexcept[0m [0mIndexError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1484[0m             [0;31m# re-raise with different error message[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1485[0;31m             [0;32mraise[0m [0mIndexError[0m[0;34m([0m[0;34m"positional indexers are out-of-bounds"[0m[0;34m)[0m [0;32mfrom[0m [0merr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1486[0m [0;34m[0m[0m
[1;32m   1487[0m     [0;32mdef[0m [0m_getitem_axis[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m,[0m [0maxis[0m[0;34m:[0m [0mint[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mIndexError[0m: positional indexers are out-of-bounds
IndexError: positional indexers are out-of-bounds

